# Copyright (c) 2024 KetiveeAI and its branches. Licensed under the KetiveeAI License.
obj-y := vfs.o fs.o
obj-$(CONFIG_FS_NXFS) += nxfs/
obj-$(CONFIG_FS_EXT4) += ext/
obj-$(CONFIG_FS_FAT) += fat/
obj-$(CONFIG_FS_NTFS) += ntfs/
obj-$(CONFIG_FS_ISO9660) += iso9660/
obj-$(CONFIG_PROC_FS) += procfs/
obj-$(CONFIG_SYS_FS) += sysfs/
obj-$(CONFIG_DEV_FS) += devfs/ 