/*
 * Generated by reoxc
 * Do not edit manually.
 */

#ifndef UI_MAIN_WINDOW_H
#define UI_MAIN_WINDOW_H

#include "../nx_minimal.h"

void ui_main_window_create(nx_window_t* window);
void ui_main_window_update_binding(const char* name, void* value);

#endif
