/*
 * MOCK Generated UI Code
 * In real build, this file is generated by reoxc from ui/main_window.reox
 */

#include "main_window.h"
#include <stdio.h>

void ui_main_window_create(nx_window_t* window) {
    // Mock implementation of UI creation
    (void)window;
    printf("[Reox] MainWindow created\n");
}

void ui_main_window_update_binding(const char* name, void* value) {
    // Mock binding update
    (void)name;
    (void)value;
    // printf("[Reox] Updated binding %s\n", name);
}
